# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."

# Temporary directory for building
tmp_dir = "tmp"

# The file name of compiled binary file
bin = "tmp/main"

# Customize binary
cmd = "go build -o ./tmp/main ./cmd/app/main.go"

# Binary file arguments
bin_args = []

# Watch these filename extensions
include_ext = ["go", "tmpl", "tpl", "html"]

# Ignore these filename extensions or directories
exclude_dir = ["assets", "tmp", "vendor"]

# Watch these directories if you specified
include_dir = []

# Exclude files or directories matching pattern
exclude_file = []

# This log file places in your tmp_dir
# log = "air.log"

# It's not necessary to trigger root when the delay is less than 1000(ms)
delay = 1000

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false

# Delay after sending Interrupt signal
kill_delay = 500
