# fly.toml app configuration file generated for ssnk-be on 2024-08-13T01:04:18+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssnk-be'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.23'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
