version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: golang:1.19.5-bullseye
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
            - v1-golang-dependencies
      - run:
          name: Install Go Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install Lint Dependencies
          command: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.0
      - save_cache:
          key: v1-golang-dependencies
          paths:
            - "/go/bin/golangci-lint"
      - run:
          name: Install Test Dependencies
          command: go install gotest.tools/gotestsum@latest
      - save_cache:
          key: v1-golang-dependencies
          paths:
            - "/go/bin/gotestsum"
      - run:
          name: Run Lint and Tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
            golangci-lint run
            cd /tmp/test-reports
            curl -Os https://uploader.codecov.io/latest/linux/codecov 
            chmod +x codecov 
            ./codecov
      - store_test_results:
          path: /tmp/test-reports

workflows:
  code_qlty:
    jobs:
      - build
