version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: golang:1.19.5-bullseye
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Go Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          path:
            - "/go/pkg/mod"
      # - run:
      #     name: Install Lint Dependencies
      #     command: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.
      #     timeout: 15
      # - save_cache:
      #     key: "v1-golang-dependencies"
      #     path:
      #       - "/go/bin/golangci-lint"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            go install gotest.tools/gotestsum@latest
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov 
            chmod +x codecov 
            ./codecov
      - store_test_results:
          path: /tmp/test-reports
      - run:
          name: Run Lint
          command: golangci-lint run --out-format=checkstyle > /tmp/test-reports/lint.xml
      - store_test_results:
          path: /tmp/test-reports

workflows:
  code_qlty:
    jobs:
      - build
