package form

// Generated by https://quicktype.io
type Message struct {
	Comment    string `json:"comment"`
	Date       string `json:"date"`
	Email      string `json:"email"`
	Meeting    bool   `json:"meeting"`
	Name       string `json:"name"`
	Newsletter bool   `json:"newsletter"`
}
