# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SonarQube analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarQube

        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args:
            -Dsonar.projectKey=${{secrets.SONAR_PROJECT_KEY}}
            -Dsonar.organization=${{secrets.SONAR_ORGANIZATION}}

      - name: Upload coverage reports to Codecov

        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          name: codecov-umbrella
          verbose: true
          run: | 
              curl -Os https://uploader.codecov.io/latest/linux/codecov 
              chmod +x codecov 
              ./codecov -t ${{ secrets.CODECOV_TOKEN }}
